NAME 			= libftprintf.a

SRCS_LIST	= ft_printf.c atoiandco.c secondutilitaries.c secondinspect.c thirdutilitaries.c convert.c typec.c  typex.c typed.c types.c typer.c inspect.c joinandcalloc.c utilitaries.c typeu.c typep.c

SRCS			= $(addprefix ${FOLDER}/, ${SRCS_LIST})

OBJS			= ${SRCS:.c=.o}

OUT				= a.out

HEADER			= header
FOLDER			= src

CC				= gcc
CFLAGS 			= -Wall -Wextra -Werror
RM				= rm -f

all:			${NAME}

$(NAME):		${OBJS}
				@ar -rcs ${NAME} ${OBJS}

%.o: %.c
				@${CC} ${CFLAGS} -I ${HEADER} -o $@ -c $<

clean:
				@${RM} ${OBJS} ${OUT}

fclean:			clean
				@${RM} ${NAME}

re:				fclean all

.PHONY: 		all fclean clean re
